# Generated by Django 3.2.8 on 2021-11-11 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prego.posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('json_body', models.JSONField(blank=True, null=True)),
                ('html_body', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ms', 'Bahasa Melayu'), ('zh', 'Zhongweng')], default='en', max_length=10)),
                ('draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=88)),
                ('summary', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=prego.posts.models.get_seo_image_path)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='posts.posttranslation')),
            ],
        ),
    ]
