# Generated by Django 3.2.9 on 2021-11-28 13:21

from django.db import migrations, models
import django.db.models.deletion
import prego.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=prego.posts.models.get_post_image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.posttranslation')),
            ],
        ),
    ]
