# Generated by Django 3.2.8 on 2021-10-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posttranslation_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postseo',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='posts.posttranslation'),
        ),
    ]
