# Generated by Django 3.2.8 on 2021-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postseo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttranslation',
            old_name='body',
            new_name='html_body',
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='json_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
