version: "3"

services:
  database:
    image: postgres:13.1-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432

  queue:
    container_name: celery_queue
    image: redis:6.2-alpine

  django_app:
    &base
    build:
      context: ../
      dockerfile: ./docker/prod.Dockerfile
    command: poetry run gunicorn blog.wsgi -c ./gunicorn.conf.py
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - database
    ports:
      - 8000:80

  celery_app:
    <<: *base
    command: poetry run celery -A blog.bg_tasks worker --loglevel=INFO
    depends_on:
      - database
      - queue
    ports: []

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
