version: "3"

services:
  database:
    image: postgres:13.1-alpine
    env_file:
      - ../.env
    ports:
      - 5400:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  queue:
    container_name: celery_queue
    image: redis:6.2-alpine

  django_app:
    &base
    image: ghcr.io/syafiqtermizi/blog:latest
    command: poetry run gunicorn blog.wsgi -c ./gunicorn.conf.py
    env_file:
      - ../.env
    depends_on:
      - database
    ports:
      - 8000:80

  celery_app:
    <<: *base
    command: poetry run celery -A blog.bg_tasks worker --loglevel=INFO
    depends_on:
      - database
      - queue
    ports: []
