---
- name: Deploy YAB to the production servers
  hosts: prod
  remote_user: "{{ project_user }}"
  roles:
    - docker_registry_login
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Create project directory if not exist
      file: 
        path: "{{ remote_project_dir }}"
        state: directory
        mode: "0755"

    - name: Copy environment files and Nginx config to the server
      template:
        src: "{{ local_project_dir }}/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: "deploy/templates/env.j2", dest: "{{ remote_project_dir }}/.env", owner: "{{ project_user }}", group: "{{ project_user }}", mode: "0755" }
        - { src: "deploy/templates/nginx.j2", dest: "/etc/nginx/sites-available/syafiqtermizi.com", owner: root, group: root, mode: "0744" }

    - name: Link Nginx config
      file:
        src: "/etc/nginx/sites-available/syafiqtermizi.com"
        dest: "/etc/nginx/sites-enabled/syafiqtermizi.com"
        state: link
        force: yes

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

    - name: Copy staticfiles and docker-compose.yml file to the server
      copy:
        src: "{{ local_project_dir }}/{{ item.src }}"
        dest: "{{ remote_project_dir }}/{{ item.dest }}"
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode: "0755"
      loop:
        - { src: "docker/prod.docker-compose.yml", dest: "docker-compose.yml"}
        - { src: "staticfiles/", dest: "staticfiles/" }

    - name: Start Docker services
      docker_compose:
        project_src: "{{ remote_project_dir }}"
        pull: yes