# Generated by Django 3.2.9 on 2022-01-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posttranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='raw_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
