# Generated by Django 3.2.10 on 2022-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posttranslation_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
